---
title: "What next"
author: "Michał Wypych"
---

## What next

You went the entire course. Congratulations! Finishing a course often leaves one with the strange feeling of "where should I go now?". This website is an opinionated list of resources you can use to further learn R and statistics

### Programming

-   [Advanced R](https://adv-r.hadley.nz/): this book delves deeper into R and some of the specifics of this programming language.
-   [Reproducible analytical pipelines in R:](https://raps-with-r.dev/) this book is a great resource for learning how to make your analyses more reproducible, how to work better with functions in R

### Statistics:

-   [PsyTeachR websites](https://psyteachr.github.io/): they cover a range of topics on statistics from basics to more complicated models. Developed by the PsyTeachR team at the University of Glasgow School of Psychology and Neuroscience. A really nice thing about them is that they provide

-   [Telling stories with data](https://tellingstorieswithdata.com/): a great book that covers the entire process of working with data from data acquisition through analysis to communication.

-   [CenterStats course on SEM](https://centerstat.org/structural-equation-modeling/): this a free 16 hour introductory course on Structural Equation Modelling with applications in R. If you are interested some of the instructors also run [a podcast on statistics.](https://quantitudepod.org/)

-   [Another course on SEM by Sacha Epskamp](http://sachaepskamp.com/SEM2020): this one goes into more advanced and detailed models but also starts from the basics.

-   [Beyond multiple regression](https://bookdown.org/roback/bookdown-BeyondMLR/): this book is a very nice introduction into setting out on the high seas beyond general linear model. It introduces generalized linear models and multilevel models in a really nice way.

#### Causal inference stuff:

-   [Causal Mixtape](https://mixtape.scunning.com/): a great introductory book on causal inference written in a clear language (though I think mainly with economists in mind so some examples might be a bit strange to non-economists) that introduces the basic terminology, issues and methods used for estimating causal effects.

-   [The Effect](https://theeffectbook.net/): another great book on introduction to causal inference. This one is (I think) written more with political scientists in mind.

-   Richard McElreath's book and [lectures](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus). This book and set of recorded lectures will make your head spin. It literally changes the way you think about the world, research and statistics. Highly recommend for slow and multiple viewing and reading.

### Blogs

Throughout this course I linked several articles from various blogs. Those are often excellent resources for learning new methods or clarifying things. Here is a collection of some of them that I find really useful and worth reading:

-   [Andrew Heiss](https://www.andrewheiss.com/blog/)

-   [Solomon Kurz](https://solomonkurz.netlify.app/blog/)

-   [Vincent Arel Bundock](https://arelbundock.com/blog.html)

-   [The 100 ci](https://www.the100.ci/)

-   [Richard McElreath](https://elevanth.org/)
